---
- name: Compliance | Scanning | Scan servers with Evaluate STIG
  hosts: "{{ limit | default('all') }}"
  gather_facts: false

  pre_tasks:
    - name: Ensure Ansible remote tmp directory exists on target
      ansible.builtin.file:
        path: /opt/ansible
        state: directory
        owner: ansible
        group: ansible
        mode: '0700'
      vars:
        ansible_pipelining: true
      become: true

    - name: Run fact gathering via stdin due to inability to use /tmp when STIGs are applied 
      ansible.builtin.setup:
      vars:
        ansible_pipelining: true

    - name: Check for Evaluate-STIG ZIP file in Linux repository
      ansible.builtin.stat:
        path: "../roles/evaluate_stig_linux/files/Evaluate-STIG.zip"
      delegate_to: localhost
      run_once: true
      register: linux_zip
      when:
        - ansible_facts['os_family'] == "RedHat" # TODO expand when other OS types supported

    - name: Check for Evaluate-STIG ZIP file in Windows repository
      ansible.builtin.stat:
        path: "../roles/evaluate_stig_windows/files/Evaluate-STIG.zip"
      delegate_to: localhost
      run_once: true
      register: windows_zip
      when:
        - ansible_facts['os_family'] == "Windows"

    - name: Check for Evaluate-STIG ZIP file in Cisco repository
      ansible.builtin.stat:
        path: "../roles/evaluate_stig_cisco/files/Evaluate-STIG.zip"
      delegate_to: localhost
      run_once: true
      register: cisco_zip
      when:
        - ansible_facts['os_family'] == "NEVER, UNKNOWN" # TODO Fix when written
    
    - name: Ensure required Linux STIG ZIP files exist
      ansible.builtin.assert:
        that:
          - linux_zip.stat.exists
        fail_msg: >-
          WARNING: One or more required 'Evaluate-STIG.zip' files are missing!
          Please manually place 'Evaluate-STIG.zip' into the 'files/' directory 
          of all active evaluation roles before running this playbook.
      delegate_to: localhost
      run_once: true
      when:
        - ansible_facts['os_family'] == "RedHat" # TODO expand when other OS types supported

    - name: Ensure required Windows STIG ZIP files exist
      ansible.builtin.assert:
        that:
          - windows_zip.stat.exists
        fail_msg: >-
          WARNING: One or more required 'Evaluate-STIG.zip' files are missing!
          Please manually place 'Evaluate-STIG.zip' into the 'files/' directory 
          of all active evaluation roles before running this playbook.
      delegate_to: localhost
      run_once: true
      when:
        - ansible_facts['os_family'] == "Windows"

    - name: Ensure required Cisco STIG ZIP files exist
      ansible.builtin.assert:
        that:
          - cisco_zip.stat.exists
        fail_msg: >-
          WARNING: One or more required 'Evaluate-STIG.zip' files are missing!
          Please manually place 'Evaluate-STIG.zip' into the 'files/' directory 
          of all active evaluation roles before running this playbook.
      delegate_to: localhost
      run_once: true
      when:
        - ansible_facts['os_family'] == "NEVER, UNKNOWN" # TODO Fix when written

  tasks:

  - name: "---------- Compliance | Scanning | Windows | Evaluate the server using Evaluate-STIG ----------"
    ansible.builtin.include_role:
      name: ../roles/evaluate_stig_windows
    vars:
      scanned_temp_dir: "C:\\Temp\\evaluate_stig_{{ ansible_date_time.epoch }}"
    when:
      - ansible_facts['os_family'] == "Windows"

  - name: "---------- Compliance | Scanning | Linux | Evaluate the server using Evaluate-STIG ----------"
    ansible.builtin.include_role:
      name: ../roles/evaluate_stig_linux
    vars:
      scanned_temp_dir: "/opt/evaluate_stig_{{ ansible_date_time.epoch }}"
    become: true
    when: 
      - ansible_facts['os_family'] == "RedHat"

  - name: "---------- Compliance | Scanning | Cisco | Evaluate the switch using Evaluate-STIG----------" # TODO - add cisco scanning
    ansible.builtin.include_role:
      name: ../roles/evaluate_stig_cisco
    vars:
      scanned_temp_dir: "/opt/evaluate_stig_{{ ansible_date_time.epoch }}"
    when:
      - ansible_facts['os_family'] == "NEVER, UNKNOWN"
      - false # UNTESTED, BLOCKING

  - name: "---------- Compliance | Storage | Upload the files to OpenRMF ----------"
    ansible.builtin.include_role:
      name: ../roles/upload_openrmf

  - name: "---------- Compliance | Storage | Upload files to NFS Server ----------"
    ansible.builtin.include_role:
      name: ../roles/upload_nfs

...